sudo: required
services:
  - docker

before_install:
  - docker build -t agrimolizzi/personal-page-test -f ./Dockerfile .

script: 
  - docker run agrimolizzi/personal-page-test npm test -- -- coverage

after_success:
  - docker build -t agrimolizzi/personal-page .
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push the image to docker hub
  - docker push agrimolizzi/personal-page
