sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t agrimolizzi/personal-page -f ./Dockerfile.dev .

script: 
  - docker run -e CI=true agrimolizzi/personal-page npm test -- --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "personal"
  env: "Personal-env"
  bucket_name: "elasticbeanstalk-us-east-2-324352693943"
  bucket_path: "personal"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"