sudo: required
services:
  - docker

before_install:
  - docker build -t agrimolizzi/personal-page-test -f ./Dockerfile .

script: 
  - docker run -e CI=true agrimolizzi/personal-page-test npm test -- --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "personal-page"
  env: "Personalpage-env"
  bucket_name: "elasticbeanstalk-us-east-2-324352693943"
  bucket_path: "personal-page"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY